feat/service-logic-methods
rose-tetteh/LibraryManagementSystem pull request #6
Opened 2024-11-17 19:39 UTC by rose-tetteh

Add methods to get list of books and add a book

2024-11-17 23:50 UTC, rose-tetteh commented
modify the database schema (add librarian table and modify properties of patron, book and library_resource)

2024-11-19 09:49 UTC, manuel-larbi requested changes

2024-11-19 09:49 UTC, manuel-larbi commented on src/main/java/com/example/librarymanagementsystem/dao/BookDAO.java
> +    }
Introduce transaction rollback to handle failures when saving data to the database.

eg.
`connection.rollback()` in the catch block.

2024-11-19 09:49 UTC, manuel-larbi commented on src/main/java/com/example/librarymanagementsystem/model/Librarian.java
> +   }
Duplicate code i think. You already have a static class in the Patron class right, then you can call that builder in here instead.

eg.
`Librarian(Patron.PatronBuilder builder)`

2024-11-19 09:49 UTC, manuel-larbi commented on src/main/java/com/example/librarymanagementsystem/dao/JournalDAO.java
> +    }
- Introduce rollback to handle transaction failures and remember to commit the changes.
- Handle specific exceptions instead of generic ones

2024-11-19 09:49 UTC, manuel-larbi commented on src/main/java/com/example/librarymanagementsystem/dao/JournalDAO.java
> +    }
Introduce rollback on each operation to handle transaction failures.

2024-11-19 13:44 UTC, rose-tetteh commented
the commit ended up in the service-classes branch

2024-11-19 15:46 UTC, manuel-larbi approved these changes

2024-11-19 15:56 UTC, manuel-larbi submitted a review, later dismissed

2024-11-19 15:58 UTC, manuel-larbi approved these changes

2024-11-19 16:38 UTC, merged